---
output:
  word_document: default
---
title: "education_R_Saldaeva"
author: "Saldaeva V"
date: "2024-09-08"
output:
  word_document:
    reference_docx: "education_R_Saldaeva"
    toc: yes
    toc_depth: 3
    toc_title: "Оглавление"


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(readxl)
library(psych)
library(ggplot2)
library(dplyr)
library(tibble)
library(tidyr)
library(rmarkdown)
```
## Работа с пакетами

```{r pressure, echo=FALSE}
.libPaths() # функция чтобы посмотреть пути к библиотекам

```

```{r Packages}
#installed.packages() # проверка какие пакеты установлены
#install.packages("package_name") # установка пакетов с CRAN
#remove.packages("package_name") # удаление пакетов
#update.packages("package_name") # обнавление пакетов
#source("https://bioconductor.org/biocLite.R") 
#biocLite("package_name") # установка пакетов с Bioconductor
#devtools::install_github("hadley/dplyr") #  установка пакетов с github
#library(package_name) # подключениe пакетов к текущему проекту
#detach(package:dplyr) # отключение пакетов к текущему проекту
```
## Чтение данных
```{r data}
data <-  read_csv2("C:\\Users\\Алексей\\Desktop\\mag\\statistics\\biostatistics\\data_csv2.csv", skip = 0, n_max = Inf)
```

## Базовые статистики
```{r data}
# mean(x, trim = 0, na.rm = TRUE)
# median(x, na.rm = TRUE)
# min(x, na.rm = FALSE)
# max(x, na.rm = FALSE)
# quantile(x, probs = seq(0, 1, 0.25), na.rm = FALSE, names = TRUE, type = 7)
# var(x, na.rm = TRUE) # дисперсия
# IQR(x, na.rm = FALSE, type = 7) # межквартильный интервал
# sum(!is.na(vec)): количество значений без учёта пропущенных;
# sum(is.na(vec)): количество пропущенных значений.
```

## Обобщающие функции
```{r data}
summary(data)
```
## Расчет статистик
```{r data}
statistics <- list(
  `Количество субъектов` = ~length(.x),
  `Количество (есть данные)` = ~sum(!is.na(.x)),
  `Нет данных` = ~sum(is.na(.x)),
  `Ср. знач.` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", mean(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
  `Станд. отклон.` = ~ifelse(sum(!is.na(.x)) < 3, "Н/П*", sd(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
  `95% ДИ для среднего` = ~sd(.x, na.rm = TRUE) %>% round(2) %>% as.character(),
  `мин. - макс.` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", paste0(min(.x, na.rm = TRUE) %>% round(2), " - ", max(.x, na.rm = TRUE) %>% round(2))),
  `Медиана` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", median(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
  `Q1 - Q3` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", paste0(quantile(.x, 0.25, na.rm = TRUE) %>% round(2), " - ", quantile(.x, 0.75, na.rm = TRUE) %>% round(2)))
)
```
